server:
  port: 9527
spring:
  application:
    name: product-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///aigou-product?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
